### ISSUE TITLE
Configure a local hook for pylint

### ISSUE THREAD

**Issue by bobuntu** [ceable/py3#3]
[Line 215](https://github.com/ceable/py3/blob/16d34dbc5877f02f19fb6384f34dce3deb62a181/.pylintrc#L215) should reflect the configurations established in `setup.cfg` under Yapf.

**Comment by bobuntu** [comment]
Here's the YAML config for it:
```yaml
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: pylint
```
